version: '3'

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 81
    ports:
      - "81:80"
    depends_on:
      - db
      - redis
  db:
    image: postgres:14.7-alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - db-data:/var/lib/postgresql/data/
  redis:
    image: redis:7.2-rc-alpine3.17
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: